//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FimFictionHistoryBrowser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Story
    {
        public int Id { get; set; }
        public string Progress { get; set; }
        public string Name { get; set; }
        public int WordCount { get; set; }
        public int ChapterCount { get; set; }
        public string Tags { get; set; }
        public string Audience { get; set; }
        public string Status { get; set; }
        public string Sequels { get; set; }
        public string Author { get; set; }
        public int Rating { get; set; }
        public string DownloadStatus { get; set; }
        public string Series { get; set; }
        public string Notes { get; set; }
        public string StoryLink { get; set; }
        public string StorageEPUB { get; set; }
    }
}
